import type { Metadata } from "next";
import { Source_Sans_3 } from 'next/font/google';

import '../styles/globals.scss';

const source_sans_3 = Source_Sans_3({
  weight: ["400", "600", "700"],
  style: "normal",
  subsets: ["latin", "cyrillic"],
  variable: '--font-source-sans-3'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${source_sans_3.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
