import type { Metadata } from "next";
import { Source_Sans_3 } from 'next/font/google';

import '../styles/globals.css';

import TheHeader from "@/components/layout/TheHeader";

const source_sans_3 = Source_Sans_3({
  weight: ["400", "600", "700"],
  style: "normal",
  subsets: ["latin", "cyrillic"],
  variable: '--font-source-sans-3'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${source_sans_3.variable} font-sans`}>
      <body className='min-w-[360px] w-full min-h-screen flex flex-col text-main text-base'>
        <header className="container flex w-full min-h-[130px] mb-1">
          <TheHeader />
        </header>
        <main className='container flex flex-col flex-grow justify-start items-center'>
          {children}
        </main>
        <footer className='min-h-[90px] flex items-end'>
          <span className='block w-full h-1 bg-blue-600'></span>
        </footer>
      </body>
    </html>
  );
}
