FROM node:16-alpine

WORKDIR /app

COPY package.json ./package.json
RUN npm install

COPY next.config.js ./next.config.js

COPY jsconfig.json ./jsconfig.json

COPY src ./src
COPY public ./public

CMD ["npm", "run", "dev"]